### PR TITLE
[Refactor] app icon

### PR DESCRIPTION
**Pull request by iaulakh**
## Purpose

* add app icon

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by phileo99** [comment]
@iaulakh  has Alex Pereira reviewed the icons?

**Comment by ShaunaSong** [comment]
> @iaulakh has Alex Pereira reviewed the icons?

Updated the icon, which is from Figma https://www.figma.com/file/BOeihN2NJE7ROdyqbihCxi/Mobile-UI-Library?node-id=3260%3A81719

**Comment by iaulakh** [comment]
@phileo99 yes, Alex shared Icon.

**Review by phileo99 — DISMISSED** [review]
tested debug and release variant
👍

**Review by ShaunaSong — DISMISSED** [review]

**Review by phileo99 — APPROVED** [review]

**Review by ShaunaSong — APPROVED** [review]

**Pull request merged**
