### PR TITLE
[Feature] Support RTL

### PR DESCRIPTION
**Pull request by ShaunaSong**
## Purpose

* Support RTL if the Locale is Arabic 

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code

1. Go to Android **Settings** and open Developers **Options Settings**
2. Under the **Drawing** settings, make sure to enable "Force RTL layout direction"** option
3. Back to App and see the RTL layout 

## What to Check
Verify that the following are valid

1. Direction Image Mirrored 
2. Layout Mirrored

## Other Information

We temporarily use dev option setting to test the feature, after Localization is done, we could use other way to test. 
|LTR - Calling Screen|RTL - Calling Screen|MS Teams RTL|
|---|---|---|
|MicrosoftTeams-image (7)|MicrosoftTeams-image (7)|MicrosoftTeams-image (6)|

### CODE REVIEW

**Comment by phileo99** [comment]
The mic drawable does not appear to be mirrored - the slash is pointing the same as non-mirrored version.  I tried on my emulator and it is the same behaviour.  Can you check with iOS to see if the mic icon is mirrored ?

**Comment by ShaunaSong** [comment]
> The mic drawable does not appear to be mirrored - the slash is pointing the same as non-mirrored version. I tried on my emulator and it is the same behaviour. Can you check with iOS to see if the mic icon is mirrored ?

Find the difference between our design and current MS Teams current behaviour. 
Will update the PR after finalizing the design.

**Comment by ShaunaSong** [comment]
>

**Review by phileo99 — APPROVED** [review]
Tested.
RTL removed from all icons in the ControlBarView and audio device list
👍

**Review by jamchengms — APPROVED** [review]

**Pull request merged**
