### PR TITLE
[Bug] Update translation string

### PR DESCRIPTION
**Pull request by ShaunaSong**
## Purpose

* Update the new string translations 
* Accessibility text for video/mic on off button

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Review by Mrayyan — DISMISSED** [review]

**Comment by iaulakh** [comment]
@ShaunaSong  are we going to merge to develop beta? or already merged

**Comment by ShaunaSong** [comment]
>

**Comment by ShaunaSong** [comment]
> @ShaunaSong are we going to merge to develop beta? or already merged

I think this translations should be in the next release so that I point it to release branch directly.

Have not merged into dev/beta

**Review by lpeixin — APPROVED** [review]

**Comment by iaulakh** [comment]
This PR has other changes from develop/beta. Luckily, all changes are required this time. :)
In future, it is possible that develop beta has additional features not required in release.

**Review by iaulakh — APPROVED** [review]

**Comment by lpx1989** [comment]
> This PR has other changes from develop/beta. Luckily, all changes are required this time. :) In future, it is possible that develop beta has additional features not required in release.

This time is ok since we are gonna bug bash it anyway so that change from develop/beta can be included as well.

**Pull request merged**
