### PR TITLE
[Feature] Dispatch cameraFailure error to subscribers

### PR DESCRIPTION
**Pull request by dhiraj**
## Purpose

* Dispatch camera start / stop / switch errors to subscribers

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull Request Checklist

- [x] Public API changes
- [ ] Verified for cross-platform
- [x] Synced with iOS, Web team
- [ ] Internal review completed
- [ ] UI Changes
  - [ ] Screen captures included
  - [ ] Tested for Light/Dark mode
  - [ ] Tested for screen rotation
  - [ ] Tested on Tablet and small screen device (5")
  - [ ] Include localization changes
- [ ] Tests
  - [ ] Memory leak analysis performed
  - [ ] Tested on API 21, 26 and latest 
  - [ ] Tested for background mode
  - [ ] Unit Tests Included
  - [ ] UI Automated Tests Included

## How to Test

* Setup an error event handler for call composite
* Setup calls and do something which causes any camera error to occur

## What to Check
Verify that the following are valid
* Error `cameraFailure` is dispatched to the event handler

### CODE REVIEW

**Review by ShaunaSong — APPROVED** [review]

**Review by Mohtasim — APPROVED** [review]

**Review by Mrayyan — APPROVED** [review]
👍

**Review by Mohtasim — COMMENTED** [review]
There is a pipeline build failure for espresso.

**Review by Mohtasim — CHANGES_REQUESTED** [review]
Please fix the espresso tests. Some of the unit tests are failing. Please fix them before merging.

**Comment by dhiraj** [comment]
> Please fix the espresso tests. Some of the unit tests are failing. Please fix them before merging.

The expresso tests had a view timeout error, so I re-ran the check and it passed this time. Let's see if this keeps happening, will investigate deeper.

**Review by Mohtasim — APPROVED** [review]
Looks good to me

**Pull request merged**
